### ISSUE TITLE
Clicking link doesn't show note

### ISSUE THREAD

**Issue by Dyldog** [mathieudutour/gatsby-digital-garden#50]
When I click a square bracket link within one of my notes, that note isn't opened (i.e: as a stacked page)

The URL is updated (in the URL bar) but the note is not shown.

**Comment by AndrewNatoli** [comment]
I'm seeing this issue as well. Seeing a past issue, #38, it looks like folks who did a fresh install before a certain date are fine.

If I watch `stackedPagesSlugs` in `react-stacked-pages-hook/hooks.tsx` the value never updates with changes in URL. At least in Edge, moving my mouse across the screen causes that declaration to re-fire, yet the updated value of `location` never makes it in.

For example, `gatsby.navigate` gets called in TK and my actual `window.location.search` becomes:

```
"?stackedPages=%2Fwaffles&stackedPages=%2Fdelicious"
```

but `location.search` exposed to `stackedPagesSlugs` remains as:

```
"?stackedPages=%2Fwaffles&stackedPages=%2Ftest"
```

**Comment by flacchini14** [comment]
have the same issue..

**Comment by mathieudutour** [comment]
Do you have a repro somewhere? The example works fine.

> Do you have a process for working on and previewing the Gatsby theme with changes to the included packages happening in real time?

Haven't had time to set up one properly, I usually just work on the node_modules of the example directly

**Comment by AndrewNatoli** [comment]
@mathieudutour Here's one I just threw together with the `gatsby new` approach:

https://andrewnatoli.github.io/gatsby-garden-theme-example

**Comment by AndrewNatoli** [comment]
Hey folks, I started messing with different versions of Gatsby after noticing `stackedPagesSlugs` was updating on the published example site but not the one I just put together. 

It turns out Gatsby [2.24.70](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#22470-2020-10-08) brought some changes to how routes are handled and it's reportedly [breaking other plugins as well](https://github.com/gatsbyjs/gatsby/pull/27261#issuecomment-705854374). There's an [issue reported](https://github.com/gatsbyjs/gatsby/issues/27351).

For now you can point the `gatsby` entry in your `package.json` to an older version such as these that I tried:

- 2.22.13
- 2.24.15
- 2.24.67

**Comment by mathieudutour** [comment]
Ah thanks for finding this!

**Comment by flacchini14** [comment]
@AndrewNatoli thannk you for finding this.
but even with <2.24.70 it doesnt work

**Comment by AndrewNatoli** [comment]
Hey @flacchini14  - Do you have an example repository you can share? Or can you post the `"gatsby":` portion of your `package-lock.json` (or `yarn.lock`) just to double check the earlier version got installed? 

I explicitly set the `gatsby` version in `package.json` without any `^` or `~` symbols, then ran:

```
rm -rf .cache && rm -rf public && npm i && npm run start
```

**Comment by Dyldog** [comment]
@AndrewNatoli Can confirm everything works if I set `gatsby` to version `2.24.67` in my `package.json`. Thank you!

**Comment by flacchini14** [comment]
thank you. it works!

**Comment by LekoArts** [comment]
Please try `gatsby@2.24.85` => https://github.com/gatsbyjs/gatsby/issues/27351#issuecomment-714319562

**Comment by mathieudutour** [comment]
Perfect, thanks 🙏
