### ISSUE TITLE
Direct links are broken 

### ISSUE THREAD

**Issue by jmg-duarte** [mathieudutour/gatsby-digital-garden#58]
Links that direct to `.md` files do not work. Sadly I am not able to pinpoint why.

Sample site: https://rustype.github.io/notes/
Corresponding repo: https://github.com/rustype/notes/

You can see the inbox link works wonders but the others don't.
The motivation behind the direct links is so that they are usable in GitHub Markdown.

**Comment by hikerpig** [comment]
Sorry, but for what I can see, you seem to be using the offcial foam template and not gatsby-digital-garden theme ? So is ther other that way that we can reproduce the bug?

**Comment by jmg-duarte** [comment]
I changed it meanwhile to use your template.
If I am not mistaken the https://github.com/rustype/notes/tree/gh-pages branch is still built with gatsby.
Furthermore this commit still has the gatsby foam https://github.com/rustype/notes/tree/2904765fddd4502d2cde0a88b4c111dccc8dd754

**Comment by hikerpig** [comment]
I checked out the gh-pages branch and am able to see it locally. I guess current behavior is somehow correct and aligned with Roam Research (guess that is the original data source), it's appropriate to not show the file extension, since we are refering to ‘topics’ rather than 'files'.

What is your expectation of the direct link's behavior ?
1. Should it be treated the same as the one wihout `.md` ext ?
2. Or should it just serves the static file with raw content of the markdown file ?

**Comment by jmg-duarte** [comment]
If the link in the `.md` file pointed to a file ending in an extension, the links would not work, that is, would not redirect and rather serve the raw file.

I understand it is necessary to compromise somewhere, the problem is simply that without the `.md` the GitHub markdown does not work and with the `.md` the site wouldn't.

Thus I switched to your Jekyll template, which works with both.

**Comment by hikerpig** [comment]
@jmg-duarte I see what the problem is. This may possibly be done by adding some options to the gatsby-digital-garden theme. Let me try for a couple a days for a proper PR in this repo.

**Comment by osukaa** [comment]
What this ever fixed? I'm having the same issue
